-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
HAVING SUM(B.PRICE) >= 700000
GROUP BY U.USER_ID, U.NICKNAME
ORDER BY TOTAL_SALES
